---
- name: Nginxコンテナの起動とステータス確認
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    container_name: nginx_web
    nginx_port: 8080
    nginx_url: "http://localhost:{{ nginx_port }}"
    retry_delay: 5    # リトライ間隔（秒）
    retry_count: 12   # 最大試行回数 (合計 60秒待機)

  tasks:
    # 1. 既存コンテナの削除と新規起動 (Port 8080:80)
    - name: 既存コンテナを強制削除 (実行前クリーンアップ)
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: Nginxコンテナをポートフォワード付きで起動
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: ubuntu/nginx:1.18-20.04_beta
        ports:
          - "{{ nginx_port }}:80"
        state: started

    # 2. URIモジュールを使ったポーリング (Nginxの起動待機)
    - name: Nginxが応答するまで待機 (ヘルスチェック)
      ansible.builtin.uri:
        url: "{{ nginx_url }}"
        method: GET
        status_code: 200 # 期待するステータスコード
        validate_certs: false
      register: result_check
      # until/retries/delayでポーリング動作を定義
      until: result_check.status == 200
      retries: "{{ retry_count }}"
      delay: "{{ retry_delay }}"

    # 3. 最終的な応答ヘッダーの表示 (curl -I に相当)
    - name: 応答ヘッダーの確認
      ansible.builtin.debug:
        msg: "Nginxが正常に応答しました。HTTPステータス: {{ result_check.status }}, サーバー情報: {{ result_check.server }}"

- name: コンテナのクリーンアップ処理 (停止と削除)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    container_name: nginx_web # 最初のPlayと同じコンテナ名を指定

  tasks:
    - name: Nginxコンテナを停止
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: stopped # コンテナを停止する

    - name: Nginxコンテナを削除
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent # コンテナを削除する (停止していなくても削除可能)